language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-9.2.7.0
  - jruby-head
  - ruby-head
matrix:
  include:
    - rvm: 1.8.7
      dist: trusty
    - rvm: 1.9.3
      dist: trusty
    - rvm: jruby-19mode
      dist: trusty
    - rvm: jruby-9.0.5.0
      dist: trusty
    - rvm: jruby-9.1.17.0
      dist: trusty
  allow_failures:
    - rvm: jruby-9.0.5.0
    - rvm: jruby-head
    - rvm: ruby-head
gemfile: .travis.gemfile
before_install:
  - gem install bundler || gem install bundler --version '< 2'
